import { NextResponse } from "next/server";
import { createAuthServerClient } from "@/lib/supabase/auth-server";
import { generateBookingsXlsx } from "@/lib/excel-export";

/**
 * GET /api/export/bookings
 *
 * Admin download of all bookings as XLSX.
 * The workbook is generated by `generateBookingsXlsx()` (shared helper also
 * used by the daily-export cron) and includes real Excel formulas for all
 * calculated positions plus Euro currency formatting.
 */
export async function GET() {
  const authSupabase = createAuthServerClient();
  const {
    data: { user },
  } = await authSupabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: profile } = await authSupabase
    .from("admin_profiles")
    .select("id")
    .eq("id", user.id)
    .single();

  if (!profile) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { buffer } = await generateBookingsXlsx();
  const today = new Date().toISOString().split("T")[0];

  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="Ferienhaus-Rita-Export-${today}.xlsx"`,
    },
  });
}
